cap program drop main
cap program drop combine_provider_level_datasets
cap program drop label_sp_variables
cap program drop label_qp_variables
cap program drop label_ind_gaming_variables

program main
    use ../../CDS_Data/prov_scan_sp.dta, clear
    combine_provider_level_datasets
    label_sp_variables
    isid provider_key
    save ../../CDS_Data/prov_all_stats_sp, replace

    use ../../CDS_Data/prov_all_stats_qp.dta, clear
    label_qp_variables
    isid provider_key
    save ../../CDS_Data/prov_all_stats_qp.dta, replace

    use ../../CDS_Data/prov_ind_gaming_sp.dta, clear
    label_ind_gaming_variables
    isid provider_key
    save ../../CDS_Data/prov_ind_gaming_sp.dta, replace
end

program combine_provider_level_datasets
    foreach var of varlist _all {
        if ("`var'" != "provider_age") & (substr("`var'",1,2) != "sh") & ("`var'" != "quit_qtr") {           
            assert !mi(`var')
        }
    }
    merge 1:1 provider_key using ../../CDS_Data/controls, assert(3) nogen
    merge 1:1 provider_key using ../../CDS_Data/prov_enc_sp, assert(3) nogen keepusing(encounter*)
    merge 1:1 provider_key using ../../CDS_Data/prov_scan_sp_quarters.dta, assert(3) nogen

    gen provider_degree_oth = provider_degree_CNM_q + provider_degree_DPM_q
    assert provider_degree_MD_q + provider_degree_DO_q + provider_degree_NP_q + provider_degree_PA_q + provider_degree_oth == 1

    sum provider_age, de
    local median_age = r(p50)

    gen prov_age_med_below = provider_age < `median_age'
    replace prov_age_med_below = . if mi(provider_age)
    gen prov_age_med_eq_above = provider_age >= `median_age'
    replace prov_age_med_eq_above = . if mi(provider_age)

    foreach enc in encounter_ed encounter_op encounter_ip_non_ed {
        replace `enc' = 0 if `enc' == .
    }
end

program label_sp_variables
    order *, alpha
    order provider_key, first
    foreach var of varlist _all {
        label var `var' ""
    }

    label var provider_key                      "Encrypted provider identifier"
    label var Iquit_qp                          "Provider left health system in the quiet period"
    label var Iquit_qtr1                        "Provider left health system in study quarter 1"
    label var Iquit_qtr2                        "Provider left health system in study quarter 2"
    label var Iquit_qtr3                        "Provider left health system in study quarter 3"
    label var Iquit_qtr4                        "Provider left health system in study quarter 4"
    label var Iquit_sp                          "Provider left health system in the study period"
    label var consent                           "Provider consented to randomization"
    label var control                           "Provider is in control group"
    label var eligible                          "Provider was eligible for randomization"
    label var encounter                         "Number encounters"
    label var encounter_ed                      "Number encounters in the ED"
    label var encounter_ed_q                    "QP number encounters in the ED"
    label var encounter_ip_non_ed               "Number encounters in the hospital, non-ED"
    label var encounter_ip_non_ed_q             "QP number encounters in the hospital, non-ED"
    label var encounter_op                      "Number encounters in an outpatient setting, non-ED"
    label var encounter_op_q                    "QP number encounters in an outpatient setting"
    label var encounter_q                       "QP number encounters"
    label var handoff_strategic_all             "Number handoffs to non-randomized and control providers"
    label var handoff_strategic_all_q           "QP number handoffs to non-randomized and control providers"
    label var handoff_strategic_not_rand        "Number handoffs to non-randomized providers"
    label var handoff_strategic_not_rand_q      "QP number handoffs to non-randomized providers"
    label var handoff_strategic_con             "Number handoffs to control providers"
    label var handoff_strategic_con_q           "QP number handoffs to control providers"
    label var most_enc_ed_q                     "Provider had most QP encounters in the ED"
    label var most_enc_ip_non_ed_q              "Provider had most QP encounters in the hospital, non-ED"
    label var most_enc_op_q                     "Provider had most QP encounters in an outpatient setting"
    label var optout                            "Provider opted-out of randomization"
    label var prov_age_23_27_q                  "Provider age is in range 23-27"
    label var prov_age_28_32_q                  "Provider age is in range 28-32"
    label var prov_age_33_37_q                  "Provider age is in range 33-37"
    label var prov_age_38_42_q                  "Provider age is in range 38-42"
    label var prov_age_43_47_q                  "Provider age is in range 43-47"
    label var prov_age_48_52_q                  "Provider age is in range 48-52"
    label var prov_age_53_57_q                  "Provider age is in range 53-57"
    label var prov_age_58_62_q                  "Provider age is in range 58-62"
    label var prov_age_63_67_q                  "Provider age is in range 63-67"
    label var prov_age_68_85_q                  "Provider age is in range 68-85"
    label var prov_age_med_below                "Provider age is below the median age"
    label var prov_age_med_eq_above             "Provider age is equal to or above the median age"
    label var provider_age                      "Provider age at start of study"
    label var provider_age_miss_q               "Missing provider age"
    label var provider_degree_CNM_q             "Provider degree is CNM"
    label var provider_degree_DO_q              "Provider degree is DO"
    label var provider_degree_DPM_q             "Provider degree is DPM"
    label var provider_degree_MD_q              "Provider degree is MD"
    label var provider_degree_NP_q              "Provider degree is NP"
    label var provider_degree_PA_q              "Provider degree is PA"
    label var provider_degree_oth               "Provider degree is CNM or DPM"
    label var provider_graduation_miss_q        "Missing years since provider graduation"
    label var provider_graduation_q             "Years since provider graduation"
    label var provider_male_miss_q              "Missing provider gender"
    label var provider_male_q                   "Provider gender is male"
    label var provider_specialty_student        "Provider is a resident"
    label var provider_specialty_assistant      "Provider is a physicians assistant"
    label var provider_specialty_gen_med        "Provider practices general medicine"
    label var provider_specialty_nurse          "Provider is a nurse"
    label var provider_specialty_specialist     "Provider has other specialty"
    label var quit_qtr                          "Qtr in which provider left health system, zeroed at start of study period"
    label var scan                              "Number scans"
    label var scan_q                            "QP number scans"
    label var scan_bd                           "Number bone densitometry scans"
    label var scan_bd_q                         "QP number bone densitometry scans"
    label var scan_bpa_new_1_3                  "Number targeted scans scored 1-3"
    label var scan_bpa_new_1_3_q                "QP number targeted scans scored 1-3"
    label var scan_bpa_new_4_6                  "Number targeted scans scored 4-6"
    label var scan_bpa_new_4_6_q                "QP number targeted scans scored 4-6"
    label var scan_bpa_new_ct                   "Number targeted CT scans"
    label var scan_bpa_new_ct_q                 "QP number targeted CT scans"
    label var scan_bpa_new                      "Number targeted scans"
    label var scan_bpa_new_q                    "QP number targeted scans"
    label var scan_bpa_new_mr                   "Number targeted MR scans"
    label var scan_bpa_new_mr_q                 "QP number targeted MR scans"
    label var scan_bpa_new_performed            "Number performed targeted scans"
    label var scan_bpa_new_performed_q          "QP number performed targeted scans"
    label var scan_bpa_old                      "Number targeted scans under the original firing logic"
    label var scan_bpa_old_q                    "QP number targeted scans under the original firing logic"
    label var scan_bpa_shut_off                 "Number scans that would trigger BPA under original but not new logic"
    label var scan_bpa_shut_off_q               "QP number scans that would trigger BPA under original but not new logic"
    label var scan_cl                           "Number canceled scans"
    label var scan_cl_q                         "QP number canceled scans"
    label var scan_ct                           "Number CT scans"
    label var scan_ct_q                         "QP number CT scans"
    label var scan_ct_cl                        "Number canceled CT scans"
    label var scan_ct_cl_q                      "QP number canceled CT scans"
    label var scan_fl                           "Number fluoroscopies"
    label var scan_fl_q                         "QP number fluoroscopies"
    label var scan_hc                           "Number high-cost scans"
    label var scan_hc_q                         "QP number high-cost scans"
    label var scan_hc_cl                        "Number canceled high-cost scans"
    label var scan_hc_cl_q                      "QP number canceled high-cost scans"
    label var scan_hc_scored_1_3_ct             "Number CT scans scored 1-3"
    label var scan_hc_scored_1_3_ct_q           "QP number CT scans scored 1-3"
    label var scan_hc_scored_1_3                "Number high-cost scans scored 1-3"
    label var scan_hc_scored_1_3_q              "QP number high-cost scans scored 1-3"
    label var scan_hc_scored_1_3_mr             "Number MR scans scored 1-3"
    label var scan_hc_scored_1_3_mr_q           "QP number MR scans scored 1-3"
    label var scan_hc_scored_1_9_ct             "Number CT scans scored 1-9"
    label var scan_hc_scored_1_9_ct_q           "QP number CT scans scored 1-9"
    label var scan_hc_scored_1_9                "Number high-cost scans scored 1-9"
    label var scan_hc_scored_1_9_q              "QP number high-cost scans scored 1-9"
    label var scan_hc_scored_1_9_mr             "Number MR scans scored 1-9"
    label var scan_hc_scored_1_9_mr_q           "QP number MR scans scored 1-9"
    label var scan_hc_scored_4_6_ct             "Number CT scans scored 4-6"
    label var scan_hc_scored_4_6_ct_q           "QP number CT scans scored 4-6"
    label var scan_hc_scored_4_6                "Number high-cost scans scored 4-6"
    label var scan_hc_scored_4_6_q              "QP number high-cost scans scored 4-6"
    label var scan_hc_scored_4_6_mr             "Number MR scans scored 4-6"
    label var scan_hc_scored_4_6_mr_q           "QP number MR scans scored 4-6"
    label var scan_hc_scored_7_9_ct             "Number CT scans scored 7-9"
    label var scan_hc_scored_7_9_ct_q           "QP number CT scans scored 7-9"
    label var scan_hc_scored_7_9                "Number high-cost scans scored 7-9"
    label var scan_hc_scored_7_9_q              "QP number high-cost scans scored 7-9"
    label var scan_hc_scored_7_9_mr             "Number MR scans scored 7-9"
    label var scan_hc_scored_7_9_mr_q           "QP number MR scans scored 7-9"
    label var scan_lowcost                      "Number low-cost scans"
    label var scan_lowcost_q                    "QP number low-cost scans"
    label var scan_mm                           "Number mammograms"
    label var scan_mm_q                         "QP number mammograms"
    label var scan_mr                           "Number MR scans"
    label var scan_mr_q                         "QP number MR scans"
    label var scan_mr_cl                        "Number canceled MR scans"
    label var scan_mr_cl_q                      "QP number canceled MR scans"
    label var scan_nm                           "Number NM scans"
    label var scan_nm_q                         "QP number NM scans"
    label var scan_order_enc_loc_ed             "Number targeted scans ordered in the ED"
    label var scan_order_enc_loc_ed_q           "QP number targeted scans ordered in the ED"
    label var scan_order_enc_loc_hosp           "Number targeted scans ordered in the hospital, non-ED"
    label var scan_order_enc_loc_hosp_q         "QP number targeted scans ordered in the hospital, non-ED"
    label var scan_order_enc_loc_oth            "Number targeted scans not ordered in person"
    label var scan_order_enc_loc_oth_q          "QP number targeted scans not ordered in person"
    label var scan_order_enc_loc_op             "Number targeted scans ordered in an outpatient setting"
    label var scan_order_enc_loc_op_q           "QP number targeted scans ordered in an outpatient setting"
    label var scan_other                        "Number other scans (not high- or low-cost)"
    label var scan_other_q                      "QP number other scans (not high- or low-cost)"
    label var scan_performed                    "Number performed scans"
    label var scan_performed_q                  "QP number performed scans"
    label var scan_pet                          "Number PET scans"
    label var scan_pet_q                        "QP number PET scans"
    label var scan_pet_nm                       "Number PET and NM scans"
    label var scan_pet_nm_q                     "QP number PET and NM scans"
    label var scan_pet_nm_cl                    "Number canceled PET and NM scans"
    label var scan_pet_nm_cl_q                  "QP number canceled PET and NM scans"
    label var scan_scored_cds                   "Number of high-cost scans scored by CDS"
    label var scan_scored_cds_q                 "QP number of high-cost scans scored by CDS"
    label var scan_scored_imp                   "Number of high-cost scans with imputed score"
    label var scan_scored_imp_q                 "QP number of high-cost scans with imputed score"
    label var scan_unscored_all                 "Number unscored HC scans"
    label var scan_unscored_all_q               "QP number unscored HC scans"
    label var scan_unscored_all_ct              "Number unscored CT scans"
    label var scan_unscored_all_ct_q            "QP number unscored CT scans"
    label var scan_unscored_all_mr              "Number unscored MR scans"
    label var scan_unscored_all_mr_q            "QP number unscored MR scans"
    label var scan_unscored_handoff_worker      "Number of HC scans unscored, handed off to a clerical worker or technician"
    label var scan_unscored_handoff_worker_q    "QP number of HC scans unscored, handed off to a clerical worker or technician"
    label var scan_unscored_custom_ind          "Number of HC scans unscored, health system custom indications"
    label var scan_unscored_custom_ind_q        "QP number of HC scans unscored, health system custom indications"
    label var scan_unscored_fltr                "Number of HC scans unscored, age-gender filters"
    label var scan_unscored_fltr_q              "QP number of HC scans unscored, age-gender filters"
    label var scan_unscored_ind_nonc            "Number of HC scans unscored, non-oncology indications ACR chose not to score"
    label var scan_unscored_ind_nonc_q          "QP number of HC scans unscored, non-oncology indications ACR chose not to score"
    label var scan_unscored_ind_onc             "Number of HC scans unscored, oncology indications ACR chose not to score"
    label var scan_unscored_ind_onc_q           "QP number of HC scans unscored, oncology indications ACR chose not to score"
    label var scan_unscored_rlst                "Number of HC scans unscored, procedures not in ruleset"
    label var scan_unscored_rlst_q              "QP number of HC scans unscored, procedures not in ruleset"
    label var scan_unscored_external            "Number HC scans unscored, order placed at external facility"
    label var scan_unscored_external_q          "QP number HC scans unscored, order placed at external facility"
    label var scan_unscored_medi                "Number of HC scans unscored, Medicalis scans"
    label var scan_unscored_medi_q              "QP number of HC scans unscored, Medicalis scans"
    label var scan_unscored_other               "Number HC scans unscored, other reasons"
    label var scan_unscored_other_q             "QP number HC scans unscored, other reasons"
    label var scan_unscored_smartset            "Number HC scans unscored, ordered in SmartSets"
    label var scan_unscored_smartset_q          "QP number HC scans unscored, ordered in SmartSets"
    label var scan_unscored_sys                 "Number of HC scans unscored, changes to electronic system build"
    label var scan_unscored_sys_q               "QP number of HC scans unscored, changes to electronic system build"
    label var scan_us                           "Number ultrasounds"
    label var scan_us_q                         "QP number ultrasounds"
    label var scan_xr                           "Number x-rays"
    label var scan_xr_q                         "QP number x-rays"
    label var treated                           "Provider is in treated group"
	** Sam new 12/19/18
	label var primary_location_id               "Primary location of SP in-person encounters"
    forval q = 1/4 {
        label var scan_bpa_new_1_3`q'           "Q`q' number targeted scans scored 1-3"
        label var scan_bpa_new_4_6`q'           "Q`q' number targeted scans scored 4-6"
        label var scan_bpa_new_ct`q'            "Q`q' number targeted CT scans"
        label var scan_bpa_new`q'               "Q`q' number targeted scans"
        label var scan_bpa_new_mr`q'            "Q`q' number targeted MR scans"
        label var scan_bpa_old`q'               "Q`q' number targeted scans under the original firing logic"
        label var scan_cl`q'                    "Q`q' number canceled scans"
        label var scan_ct`q'                    "Q`q' number CT scans"
        label var scan_ct_cl`q'                 "Q`q' number canceled CT scans"
        label var scan_hc`q'                    "Q`q' number high-cost scans"
        label var scan_hc_cl`q'                 "Q`q' number canceled high-cost scans"
        label var scan_hc_scored_1_3_ct`q'      "Q`q' number CT scans scored 1-3"
        label var scan_hc_scored_1_3`q'         "Q`q' number high-cost scans scored 1-3"
        label var scan_hc_scored_1_3_mr`q'      "Q`q' number MR scans scored 1-3"
        label var scan_hc_scored_1_9_ct`q'      "Q`q' number CT scans scored 1-9"
        label var scan_hc_scored_1_9`q'         "Q`q' number high-cost scans scored 1-9"
        label var scan_hc_scored_1_9_mr`q'      "Q`q' number MR scans scored 1-9"
        label var scan_hc_scored_4_6_ct`q'      "Q`q' number CT scans scored 4-6"
        label var scan_hc_scored_4_6`q'         "Q`q' number high-cost scans scored 4-6"
        label var scan_hc_scored_4_6_mr`q'      "Q`q' number MR scans scored 4-6"
        label var scan_hc_scored_7_9_ct`q'      "Q`q' number CT scans scored 7-9"
        label var scan_hc_scored_7_9`q'         "Q`q' number high-cost scans scored 7-9"
        label var scan_hc_scored_7_9_mr`q'      "Q`q' number MR scans scored 7-9"
        label var scan_lowcost`q'               "Q`q' number low-cost scans"
        label var scan_mr`q'                    "Q`q' number MR scans"
        label var scan_mr_cl`q'                 "Q`q' number canceled MR scans"
        label var scan_pet_nm`q'                "Q`q' number PET and NM scans"
        label var scan_pet_nm_cl`q'             "Q`q' number canceled PET and NM scans"
    }
end

program label_qp_variables
    order *, alpha
    order provider_key, first
    foreach var of varlist _all {
        label var `var' ""
    }
    label var provider_key                      "Encrypted provider identifier"
    label var consent                           "Provider consented to randomization"
    label var control                           "Provider is in control group"
    label var eligible                          "Provider was eligible for randomization"
    label var encounter                         "QP number encounters"
    label var encounter_ed                      "QP number encounters in the ED"
    label var encounter_ip_non_ed               "QP number encounters in the hospital, non-ED"
    label var encounter_op                      "QP number encounters in an outpatient setting"
    label var handoff_strategic_all             "QP number handoffs to non-randomized and control providers"
    label var handoff_strategic_not_rand        "QP number handoffs to non-randomized providers"
    label var handoff_strategic_con             "QP number handoffs to control providers"
    label var most_enc_ed                       "Provider had most QP encounters in the ED"
    label var most_enc_ip_non_ed                "Provider had most QP encounters in the hospital, non-ED"
    label var most_enc_op                       "Provider had most QP encounters in an outpatient setting"
    label var optout                            "Provider opted-out of randomization"
    label var pat_table_age                     "QP average age of patients for whom provider had an encounter"
    label var pat_table_male                    "QP share of patients for whom provider had an encounter who are male"
    label var pat_table_white                   "QP share of patients for whom provider had an encounter who are white"
    label var provider_age                      "Provider age at start of study"
    label var provider_age_miss                 "Missing provider age"
    label var provider_degree_CNM               "Provider degree is CNM"
    label var provider_degree_DO                "Provider degree is DO"
    label var provider_degree_DPM               "Provider degree is DPM"
    label var provider_degree_MD                "Provider degree is MD"
    label var provider_degree_NP                "Provider degree is NP"
    label var provider_degree_PA                "Provider degree is PA"
    label var provider_graduation               "Years since provider graduation"
    label var provider_graduation_miss          "Missing provider graduation year"
    label var provider_male                     "Provider gender is male"
    label var provider_male_miss                "Missing provider gender"
    label var provider_specialty_student        "Provider is a resident"
    label var provider_specialty_assistant      "Provider is a physicians assistant"
    label var provider_specialty_gen_med        "Provider practices general medicine"
    label var provider_specialty_nurse          "Provider is a nurse"
    label var provider_specialty_specialist     "Provider has other specialty"
    label var scan                              "QP number scans"
    label var scan_bd                           "QP number bone densitometry scans"
    label var scan_bpa_eligible_annualized      "QP number targeted scans, annualized"
    label var scan_bpa_new_1_3                  "QP number targeted scans scored 1-3"
    label var scan_bpa_new_4_6                  "QP number targeted scans scored 4-6"
    label var scan_bpa_new_ct                   "QP number targeted CT scans"
    label var scan_bpa_new                      "QP number targeted scans"
    label var scan_bpa_new_mr                   "QP number targeted MR scans"
    label var scan_bpa_new_performed            "QP number performed targeted scans"
    label var scan_bpa_old                      "QP number targeted scans under the original firing logic"
    label var scan_bpa_shut_off                 "QP number scans that would trigger BPA under original but not new logic"
    label var scan_cl                           "QP number canceled scans"
    label var scan_ct                           "QP number CT scans"
    label var scan_ct_cl                        "QP number canceled CT scans"
    label var scan_fl                           "QP number fluoroscopies"
    label var scan_hc                           "QP number high-cost scans"
    label var scan_hc_annualized                "QP number high-cost scans, annualized"
    label var scan_hc_cl                        "QP number canceled high-cost scans"
    label var scan_hc_scored_1_3_ct             "QP number CT scans scored 1-3"
    label var scan_hc_scored_1_3                "QP number high-cost scans scored 1-3"
    label var scan_hc_scored_1_3_mr             "QP number MR scans scored 1-3"
    label var scan_hc_scored_1_9_ct             "QP number CT scans scored 1-9"
    label var scan_hc_scored_1_9                "QP number high-cost scans scored 1-9"
    label var scan_hc_scored_1_9_mr             "QP number MR scans scored 1-9"
    label var scan_hc_scored_4_6_ct             "QP number CT scans scored 4-6"
    label var scan_hc_scored_4_6                "QP number high-cost scans scored 4-6"
    label var scan_hc_scored_4_6_mr             "QP number MR scans scored 4-6"
    label var scan_hc_scored_7_9_ct             "QP number CT scans scored 7-9"
    label var scan_hc_scored_7_9                "QP number high-cost scans scored 7-9"
    label var scan_hc_scored_7_9_mr             "QP number MR scans scored 7-9"
    label var scan_lowcost                      "QP number low-cost scans"
    label var scan_mm                           "QP number mammograms"
    label var scan_mr                           "QP number MR scans"
    label var scan_mr_cl                        "QP number canceled MR scans"
    label var scan_nm                           "QP number NM scans"
    label var scan_order_enc_loc_ed             "QP number targeted scans ordered in the ED"
    label var scan_order_enc_loc_hosp           "QP number targeted scans ordered in the hospital, non-ED"
    label var scan_order_enc_loc_op             "QP number targeted scans ordered in an outpatient setting"
    label var scan_order_enc_loc_oth            "QP number targeted scans not ordered in person"
    label var scan_other                        "QP number other scans (not high- or low-cost)"
    label var scan_performed                    "QP number performed scans"
    label var scan_pet                          "QP number PET scans"
    label var scan_pet_nm                       "QP number PET and NM scans"
    label var scan_pet_nm_cl                    "QP number canceled PET and NM scans"
    label var scan_scored_cds                   "QP number of high-cost scans scored by CDS"
    label var scan_scored_imp                   "QP number of high-cost scans with imputed score"
    label var scan_unscored_all                 "QP number unscored HC scans"
    label var scan_unscored_all_ct              "QP number unscored CT scans"
    label var scan_unscored_all_mr              "QP number unscored MR scans"
    label var scan_unscored_handoff_worker      "QP number of HC scans unscored, handed off to a clerical worker or technician"
    label var scan_unscored_custom_ind          "QP number of HC scans unscored, health system custom indications"
    label var scan_unscored_fltr                "QP number of HC scans unscored, age-gender filters"
    label var scan_unscored_ind_nonc            "QP number of HC scans unscored, non-oncology indications ACR chose not to score"
    label var scan_unscored_ind_onc             "QP number of HC scans unscored, oncology indications ACR chose not to score"
    label var scan_unscored_rlst                "QP number of HC scans unscored, procedures not in ruleset"
    label var scan_unscored_external            "QP number HC scans unscored, order placed at external facility"
    label var scan_unscored_medi                "QP number of HC scans unscored, Medicalis scans"
    label var scan_unscored_other               "QP number HC scans unscored, other reasons"
    label var scan_unscored_smartset            "QP number HC scans unscored, ordered in SmartSets"
    label var scan_unscored_sys                 "QP number of HC scans unscored, changes to electronic system build"
    label var scan_us                           "QP number ultrasounds"
    label var scan_xr                           "QP number x-rays"
    label var treated                           "Provider is in treated group"
end

program label_ind_gaming_variables
    order *, alpha
    order provider_key, first
    foreach var of varlist _all {
        label var `var' ""
    }
    label var provider_key                      "Encrypted provider identifier"
    label var consent                           "Provider consented to randomization"
    label var control                           "Provider is in control group"
    label var ind_abd_pain                      "# scored HC scans w/ ind 'Abdominal pain'"
    label var ind_abd_rlq                       "# scored HC scans w/ ind 'Abdominal pain, RLQ'"
    label var ind_ams                           "# scored HC scans w/ ind 'Altered mental status'"
    label var ind_chest_pain                    "# scored HC scans w/ ind 'Chest pain, acute, PE suspected'"
    label var ind_confusion                     "# scored HC scans w/ ind 'Confusion/delirium, altered LOC, unexplained'"
    label var ind_cspine_high                   "# scored HC scans w/ ind 'C-spine trauma, NEXUS/CCR positive, +risk factor(s)'"
    label var ind_cspine_low                    "# scored HC scans w/ ind 'C-spine trauma, NEXUS/CCR negative, low risk'"
    label var ind_dizziness                     "# scored HC scans w/ ind 'Dizziness'"
    label var ind_el_ddimer                     "# scored HC scans w/ ind 'Elevated D-dimer, mod-high risk'"
    label var ind_flank_stone                   "# scored HC scans w/ ind 'Flank pain, stone known or suspected'"
    label var ind_head_new                      "# scored HC scans w/ ind 'Headache, chronic, new features or neuro deficit'"
    label var ind_head_norm                     "# scored HC scans w/ ind 'Headache, chronic, no new features, norm neuro exam'"
    label var ind_head_thund                    "# scored HC scans w/ ind 'Headache, acute, severe, thunderclap, worst HA of..'"
    label var ind_hematuria                     "# scored HC scans w/ ind 'Hematuria'"
    label var ind_kidney_stone                  "# scored HC scans w/ ind 'Kidney stone'"
    label var ind_knee_pain                     "# scored HC scans w/ ind 'Knee pain, persistent, >=6wks'"
    label var ind_lower_back                    "# scored HC scans w/ ind 'Low back pain, <6 wks or red flag(s) or radiculopathy'"
    label var ind_lung_geq_1                    "# scored HC scans w/ ind 'Lung nodule, >=1cm'"
    label var ind_lung_less_1                   "# scored HC scans w/ ind 'Lung nodule, <1cm'"
    label var ind_mild_head                     "# scored HC scans w/ ind 'Head injury mild or moderate acute, no neurological..'"
    label var ind_mod_head                      "# scored HC scans w/ ind 'Head trauma, closed, mod-severe'"
    label var ind_neck_pain                     "# scored HC scans w/ ind 'Neck pain, first study'"
    label var ind_other                         "# scored HC scans w/ other indications"
    label var ind_post_trauma                   "# scored HC scans w/ ind 'Headache, post trauma'"
    label var ind_radiculopathy                 "# scored HC scans w/ ind 'RADICULOPATHY'"
    label var ind_short_breath                  "# scored HC scans w/ ind 'Shortness of breath'"
    label var ind_shoulder_pers                 "# scored HC scans w/ ind 'Shoulder pain, prior xray, persistent'"
    label var ind_shoulder_rotator              "# scored HC scans w/ ind 'Shoulder pain, prior xray, suspect rotator...'"
    label var ind_sinusitis                     "# scored HC scans w/ ind 'Sinusitis, recurring, possible surgery'"
    label var ind_stroke                        "# scored HC scans w/ ind 'Stroke'"
    label var ind_tobacco                       "# scored HC scans w/ ind 'Tobacco use - asymptomatic'"

    label var sh_ind_abd_pain                    "Share scored HC scans w/ ind 'Abdominal pain'"
    label var sh_ind_abd_rlq                     "Share scored HC scans w/ ind 'Abdominal pain, RLQ'"
    label var sh_ind_ams                         "Share scored HC scans w/ ind 'Altered mental status'"
    label var sh_ind_chest_pain                  "Share scored HC scans w/ ind 'Chest pain, acute, PE suspected'"
    label var sh_ind_confusion                   "Share scored HC scans w/ ind 'Confusion/delirium, altered LOC, unexplained'"
    label var sh_ind_cspine_high                 "Share scored HC scans w/ ind 'C-spine trauma, NEXUS/CCR positive, +risk fact...'"
    label var sh_ind_cspine_low                  "Share scored HC scans w/ ind 'C-spine trauma, NEXUS/CCR negative, low risk'"
    label var sh_ind_dizziness                   "Share scored HC scans w/ ind 'Dizziness'"
    label var sh_ind_el_ddimer                   "Share scored HC scans w/ ind 'Elevated D-dimer, mod-high risk'"
    label var sh_ind_flank_stone                 "Share scored HC scans w/ ind 'Flank pain, stone known or suspected'"
    label var sh_ind_head_new                    "Share scored HC scans w/ ind 'Headache, chronic, new features or neuro deficit'"
    label var sh_ind_head_norm                   "Share scored HC scans w/ ind 'Headache, chronic, no new features, norm neuro...'"
    label var sh_ind_head_thund                  "Share scored HC scans w/ ind 'Headache, acute, severe, thunderclap, worst HA...'"
    label var sh_ind_hematuria                   "Share scored HC scans w/ ind 'Hematuria'"
    label var sh_ind_kidney_stone                "Share scored HC scans w/ ind 'Kidney stone'"
    label var sh_ind_knee_pain                   "Share scored HC scans w/ ind 'Knee pain, persistent, >=6wks'"
    label var sh_ind_lower_back                  "Share scored HC scans w/ ind 'Low back pain, <6 wks or red flag(s) or radicu...'"
    label var sh_ind_lung_geq_1                  "Share scored HC scans w/ ind 'Lung nodule, >=1cm'"
    label var sh_ind_lung_less_1                 "Share scored HC scans w/ ind 'Lung nodule, <1cm'"
    label var sh_ind_mild_head                   "Share scored HC scans w/ ind 'Head injury mild or moderate acute, no neurolo...'"
    label var sh_ind_mod_head                    "Share scored HC scans w/ ind 'Head trauma, closed, mod-severe'"
    label var sh_ind_neck_pain                   "Share scored HC scans w/ ind 'Neck pain, first study'"
    label var sh_ind_other                       "Share scored HC scans w/ other indications"
    label var sh_ind_post_trauma                 "Share scored HC scans w/ ind 'Headache, post trauma'"
    label var sh_ind_radiculopathy               "Share scored HC scans w/ ind 'RADICULOPATHY'"
    label var sh_ind_short_breath                "Share scored HC scans w/ ind 'Shortness of breath'"
    label var sh_ind_shoulder_pers               "Share scored HC scans w/ ind 'Shoulder pain, prior xray, persistent'"
    label var sh_ind_shoulder_rotator            "Share scored HC scans w/ ind 'Shoulder pain, prior xray, suspect rotator...'"
    label var sh_ind_sinusitis                   "Share scored HC scans w/ ind 'Sinusitis, recurring, possible surgery'"
    label var sh_ind_stroke                      "Share scored HC scans w/ ind 'Stroke'"
    label var sh_ind_tobacco                     "Share scored HC scans w/ ind 'Tobacco use - asymptomatic'"

    label var treated                           "Provider is in treated group"
    label var total_ind                          "# scored HC scans, missing if 0"
end

*Execute
main
